### ISSUE TITLE
Update 'Game Saved' message on Game Page to fade in and out, rather than pop in and out.

### ISSUE THREAD

**Issue by CMPSCjg** [CMPSCjg/CookieCloner#28]
Would just need to update the implementation to gradually increase the opacity to 100% and then gradually decrease it back to 0.

**Comment by nullmaxwell** [comment]
Moving the location of this banner may look better as well. Possibly to above the cookie?

**Comment by CMPSCjg** [comment]
@nullmaxwell Agreed. Let's move the position/location too.

**Comment by CMPSCjg** [comment]
Picking this up.

**Comment by CMPSCjg** [comment]
Created PR : https://github.com/CMPSCjg/CookieCloner/pull/36
